"""The collator's checkpoints are judged against the checkpoint schema.

The emitter lives in Go and the schema is a file in contract/, so
nothing on either side can prove the pact alone: a Go re-implementation
of the shapes would be that package agreeing with itself, and a
committed sample would keep validating long after the emitter stopped
agreeing with it — the fourth-copy defect wearing a test fixture.

So the samples are GENERATED by the same WriteCheckpoint the wire uses,
and validated here against contract/se.checkpoint.1.json itself.

Coverage, stated because a guard that hides its edges is this estate's
most repeated defect, and measured here by reverting the emitter three
ways on 2026-08-20 and watching which tests fell over:

- an omitted `history_gap` and a dropped `instance` are both caught here;
- **a manifest that under-reports is NOT**, and cannot be. Only the Go
  suite caught that one, and the reason is structural rather than an
  omission to fix: the manifest is the receiver's ONLY account of what
  the sender declares, so nothing downstream can tell a complete
  manifest from one missing a collection. The manifest makes the
  STREAM's completeness falsifiable — terminal count against manifest
  entries, which this file does check — and its own completeness is a
  claim that has to be trusted. That is exactly why the rule lives on
  the sender, next to the store that knows the answer, in
  TestManifestNamesNeverAppliedCollections.

It also does not prove a hub accepts any of it, which needs a hub.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest
from jsonschema import Draft202012Validator
from referencing import Registry, Resource

REPO = Path(__file__).resolve().parent.parent
CONTRACT = REPO / "contract"


def _validator() -> Draft202012Validator:
    registry = Registry()
    for path in sorted(CONTRACT.glob("*.json")):
        schema = json.loads(path.read_text())
        registry = registry.with_resource(schema["$id"], Resource.from_contents(schema))
    schema = json.loads((CONTRACT / "se.checkpoint.1.json").read_text())
    return Draft202012Validator(schema, registry=registry)


def emit_samples() -> dict[str, list[dict]]:
    """Run the Go emitter and return every sample it wrote, parsed.

    Shared with the receiver suite, so both judge the SAME bytes: a
    receiver proven against hand-written records would be proven against
    somebody's idea of the emitter rather than against the emitter.
    """
    go = shutil.which("go")
    if go is None:
        pytest.skip("go toolchain not present")
    out = Path(tempfile.mkdtemp(prefix="se-checkpoint-samples"))
    run = subprocess.run(
        [go, "test", "./internal/collate/", "-count=1",
         "-run", "TestEmitsConformanceSamples|TestEmitsSessionSamples"],
        cwd=REPO / "go",
        env={**os.environ, "SE_CHECKPOINT_SAMPLES": str(out)},
        capture_output=True,
        text=True,
    )
    assert run.returncode == 0, f"emitting samples failed:\n{run.stdout}\n{run.stderr}"
    files = sorted(out.glob("*.jsonl"))
    assert files, (
        "the emitter produced no samples — a green run over an empty set is "
        "the vacuous pass this suite exists to refuse"
    )
    parsed = {p.stem: [json.loads(line) for line in p.read_text().splitlines() if line.strip()]
              for p in files}
    for p in sorted((out / "sessions").glob("*.jsonl")):
        parsed["session:" + p.stem] = [
            json.loads(line) for line in p.read_text().splitlines() if line.strip()
        ]
    return parsed


def checkpoints_only(samples: dict[str, list[dict]]) -> dict[str, list[dict]]:
    """Drop the session samples' declaration framing.

    A session opens with records the checkpoint schema has never heard of,
    deliberately — the framing CARRIES a declaration and is not one — so
    the checkpoint half is what this file judges, and the framing is
    judged where it is consumed, in the session suite.
    """
    out = {}
    for name, records in samples.items():
        kept = [r for r in records if r.get("record") != "declaration"]
        if kept:
            out[name] = kept
    return out


@pytest.fixture(scope="module")
def samples() -> dict[str, list[dict]]:
    return emit_samples()


def test_every_record_validates(samples: dict[str, list[dict]]) -> None:
    validator = _validator()
    for name, records in checkpoints_only(samples).items():
        assert records, f"{name}: no records"
        for i, record in enumerate(records):
            errors = sorted(validator.iter_errors(record), key=str)
            assert not errors, f"{name}[{i}] ({record.get('record')}):\n" + "\n".join(
                f"- {e.json_path}: {e.message}" for e in errors
            )


def test_each_checkpoint_is_well_formed(samples: dict[str, list[dict]]) -> None:
    """The rules that span records, which no single-record schema can hold."""
    for name, records in checkpoints_only(samples).items():
        assert records[0]["record"] == "manifest", f"{name}: opens with a manifest"
        assert records[-1]["record"] == "terminal", f"{name}: closes with a terminal"
        ids = {r["checkpoint"] for r in records}
        assert len(ids) == 1, f"{name}: two checkpoints interleaved: {ids}"

        manifest = records[0]
        states = [r for r in records if r["record"] == "collection_state"]
        assert records[-1]["collections"] == len(states), (
            f"{name}: the terminal counts what was actually sent"
        )
        assert "history_gap" in records[-1], f"{name}: history_gap is stated, never omitted"

        declared = {e["collection"]: e for e in manifest["collections"]}
        for state in states:
            entry = declared.get(state["collection"])
            assert entry is not None, (
                f"{name}: {state['collection']} sent state and the manifest does not name it"
            )
            assert entry["generation"] == state["generation"], (
                f"{name}: {state['collection']} state is under a generation the manifest "
                "does not claim — a checkpoint that moved while it was being sent"
            )
            assert entry.get("objects") == len(state["objects"]), (
                f"{name}: {state['collection']} promised {entry.get('objects')} objects "
                f"and sent {len(state['objects'])}"
            )
        # Every collection the manifest names at generation 0 sends no
        # state, and every one above 0 sends exactly one.
        sent = {s["collection"] for s in states}
        for collection, entry in declared.items():
            if entry["generation"] == 0:
                assert collection not in sent, (
                    f"{name}: {collection} has never applied and sent state anyway"
                )
            else:
                assert collection in sent, (
                    f"{name}: {collection} is applied at generation "
                    f"{entry['generation']} and sent no state"
                )


def test_two_instances_stay_two_objects(samples: dict[str, list[dict]]) -> None:
    """Acceptance item 1 as the hub will receive it: the minted id repeats,
    and `instance` is the whole of what keeps the two apart."""
    records = samples["two-instances"]
    objects = [r for r in records if r["record"] == "collection_state"][0]["objects"]
    assert len(objects) == 2, objects
    assert objects[0]["id"] == objects[1]["id"], "the identical id is the premise"
    assert all("instance" in o for o in objects), (
        "an absent member meaning host-native is the magic value the identity "
        "model refuses"
    )
    assert {json.dumps(o["instance"]) for o in objects} == {"null", '"radarr"'}
