"""The committed corpus must survive the independent leak detectors.

Every file a variant ships — payloads, the expected stream, meta.json — is
swept by the detectors the publish gate runs (se_harness/detectors.py). The
scrubber cannot vouch for itself: this suite is the second opinion applied to
what is actually committed, so a leak that slipped a past scrub run stays red
until somebody removes it, not until somebody re-runs the tool that missed it.

A red run here is a leak report, never a known state. The corpus was
regenerated by the keyed manifest-driven scrubber (manifests live in
harness/scrub/<collector>.json), so every committed specimen has passed the
detectors once — a finding now means one of exactly two things, and both
demand action before anything else ships: identifying material has reached
the tree (remove it, then ask how it got past the scrub), or a detector has
lost precision (repair it in detectors.py and pin the false positive there
as a quiet case). Skipping or expecting a red case re-opens the publish gate.

The manifest's single contribution here is one boolean per collector: a file
whose manifest declares address fields may carry in-space private
replacements; one that declares none may carry no private address at all.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from se_harness import corpus, detectors

REPO = Path(__file__).resolve().parent.parent
CORPUS = REPO / "corpus"
SCRUB_MANIFESTS = REPO / "harness" / "scrub"


def _declares_addresses(collector: str) -> bool:
    manifest = SCRUB_MANIFESTS / f"{collector}.json"
    if not manifest.exists():
        # no manifest yet: deny-by-default, a private address is a finding
        return False
    return any(
        entry.get("format") in ("ipv4", "ipv6")
        and entry.get("discloses") != "nothing"
        for key, entry in json.loads(manifest.read_text()).items()
        if not key.startswith("#") and isinstance(entry, dict)
    )


def test_every_collector_in_the_corpus_has_a_scrub_manifest() -> None:
    """A collector whose corpus was committed without one is unswept.

    The scrubber is deny-by-default twice over — it refuses to run without a
    manifest, and its walk fails on any leaf no entry classifies — so a
    manifest is what makes a capture publishable at all. But nothing required
    one to EXIST. A collector whose payloads reached the tree by another
    route would be a corpus nobody classified, and the one boolean the
    detectors read from the manifest (`_declares_addresses`) would quietly
    answer False for it, which reads as "declares no address fields" rather
    than "was never classified".

    The manifest may legitimately declare that a payload discloses nothing —
    the system collector's os-release entry does — but that is a decision
    somebody wrote down, which is the whole difference.
    """
    collectors = {
        json.loads(p.read_text()).get("collector")
        for p in sorted(CORPUS.rglob("meta.json"))
    }
    assert collectors, "no corpus collectors; this check grades nothing"
    missing = sorted(
        c for c in collectors if not (SCRUB_MANIFESTS / f"{c}.json").exists()
    )
    assert not missing, (
        f"{missing} ship corpus payloads with no scrub manifest at "
        f"harness/scrub/<collector>.json. Absence of a manifest is not "
        "absence of a credential surface — it is absence of anyone having "
        "looked, and the detectors' address rule reads it as the former."
    )


def _cases() -> list[pytest.param]:
    # The variant directories are walked directly, not through
    # corpus.load_variant(): this gate judges what is COMMITTED, and a file
    # must not escape the sweep because the loader rejects its variant for
    # some unrelated reason (missing meta members, an empty stream). The one
    # piece of loader knowledge reused is the stream decoding, so pretty-
    # printed and one-per-line records both keep working.
    cases = []
    for meta_path in sorted(CORPUS.rglob("meta.json")):
        variant_dir = meta_path.parent
        meta = json.loads(meta_path.read_text())
        name = f"{variant_dir.parent.name}/{variant_dir.name}"
        declares = _declares_addresses(str(meta.get("collector", "")))
        for payload in sorted((variant_dir / "payloads").iterdir()):
            if not payload.is_file() or payload.name.startswith("."):
                continue  # .gitkeep is git plumbing, not a capture
            if payload.suffix == ".json":
                document: object = json.loads(payload.read_text())
            else:
                # Text payloads are swept as {stem: text}: a *.json glob here
                # was the subset-guard shape — the system collector's payloads
                # are os-release, hostname and boot_id, and every one of them
                # escaped the sweep entirely. The stem is the document's one
                # name, and wrapping arms the detectors' id-ish key context:
                # a boot_id file holds a UUID that reads as an identifier
                # precisely because of what the file is called.
                document = {payload.stem: payload.read_text()}
            cases.append(pytest.param(
                document, declares,
                id=f"{name}/payloads/{payload.name}",
            ))
        expected = variant_dir / "expected.jsonl"
        if expected.exists():
            cases.append(pytest.param(
                corpus._read_stream(expected), declares, id=f"{name}/expected"
            ))
        cases.append(pytest.param(meta, declares, id=f"{name}/meta"))
    return cases


@pytest.mark.parametrize("document,declares_addresses", _cases())
def test_no_detector_fires_on_committed_corpus(document, declares_addresses) -> None:
    findings = detectors.scan(document, declares_address_fields=declares_addresses)
    assert not findings, "committed corpus carries identifying material:\n" + "\n".join(
        f"  {f.path} [{f.value_class}] {f.why}" for f in findings
    )
