"""Each lab variant kills the defect it was staged for.

A variant earns its bytes by failing a subject that is wrong about the machine
(DESIGN 20). Determinism is not that: the expected half is generated by the
reference, so a pair agreeing with itself proves only that the reference is a
function. The anchors are the planted truth, and this is where they are made
to bite — each staged variant is put in front of the wrong answer its staging
was designed to expose, and the ANCHORS must report it, naming the fact.

**The defects are modelled on the stream, and that is deliberate.** The
obvious subject is the committed adversary, fixtures/adversaries/
a5_hardcoded_healthy.py, whose defect list is where three of the four cases
below come from. It cannot serve here: it predates the tokenised
`<collection>:<generation>` request line, so it publishes its objects under
the collection name `nft-chains:100` and EVERY anchor fails with "no object
named … in 'nft-chains'" — a red that would survive deleting the staging
entirely, which is the vacuity this module exists to refuse. So each case
applies the wrong implementation's own transformation to a correct stream:
one defect at a time, everything else right, and the anchor that must catch
it named in the assertion.

The reference is the positive control for all of them, over the whole corpus,
so a red below is a subject failing and never an anchor nobody can satisfy.
"""

from __future__ import annotations

import pytest

from se_harness import corpus, replay

VARIANTS = {v.name: v for v in corpus.all_variants()}


def _reference_stream(name: str) -> list[dict]:
    variant = VARIANTS[name]
    proc = replay.run_collector(replay.reference_binary(), variant)
    assert proc.returncode == 0, f"{name}: reference exited {proc.returncode}"
    return replay.parse_stream(proc.stdout)


def _rewrite(records: list[dict], name: str, change) -> list[dict]:
    """One object's facts, as some wrong implementation would have built them."""
    out, seen = [], False
    for record in records:
        if record.get("record") == "object" and record.get("name") == name:
            seen = True
            record = {**record, "facts": change(dict(record["facts"]))}
        out.append(record)
    assert seen, f"no object named {name!r} to rewrite — the model is stale"
    return out


def _unreachable(facts: dict) -> dict:
    """What a reachability walk that cannot see the arriving verdict emits.

    Both members, because they are one answer: dropping JumpedFrom without
    adding Unreferenced would be a subject that says nothing rather than a
    subject that says the wrong thing, and only the second is the defect.
    """
    facts.pop("JumpedFrom", None)
    facts["Unreferenced"] = True
    return facts


@pytest.mark.parametrize("name", sorted(VARIANTS))
def test_the_reference_satisfies_every_variants_anchors(name: str) -> None:
    """Positive control, over every variant in the corpus."""
    assert not corpus.validate_anchors(VARIANTS[name], _reference_stream(name))


@pytest.mark.parametrize(
    "name,chain",
    [
        # a5 defect N1: JumpedFrom built from `jump` alone. goto differs from
        # jump in where control RETURNS, not in whether it arrives.
        ("network/goto", "inet gotolab dispatch"),
        # The same defect one spelling further out: the jump sits in a named
        # map's elem list, which no rule expression contains at all.
        ("network/named-map", "inet maplab landing"),
    ],
)
def test_a_chain_wrongly_called_unreachable_fails_the_anchors(
    name: str, chain: str
) -> None:
    """Unreferenced is the fact somebody deletes a chain on the strength of."""
    problems = corpus.validate_anchors(
        VARIANTS[name], _rewrite(_reference_stream(name), chain, _unreachable)
    )
    assert any("JumpedFrom" in p for p in problems), problems
    assert any("Unreferenced" in p for p in problems), problems


def test_the_asymmetric_anchors_catch_a_name_keyed_reachability_walk() -> None:
    """One chain name, two families: the walk that answers for both at once.

    A walk that records `jumped to shared` without the family and table it
    was written in is wrong about exactly one of the two copies whichever way
    it errs — the live v4 chain reported dead, or the dead v6 chain reported
    live — so the variant anchors both, and each direction is required to be
    caught on its own.
    """
    correct = _reference_stream("network/asymmetric")
    variant = VARIANTS["network/asymmetric"]

    def reachable(facts: dict) -> dict:
        facts.pop("Unreferenced", None)
        facts["JumpedFrom"] = ["input"]
        return facts

    assert corpus.validate_anchors(
        variant, _rewrite(correct, "ip6 asym shared", reachable)
    ), (
        "the ip6 chain wearing the ip chain's reachability satisfied the "
        "anchors — an unreferenced chain reported as reached, which is the "
        "answer somebody leaves a dead rule in place on"
    )
    assert corpus.validate_anchors(
        variant, _rewrite(correct, "ip asym shared", _unreachable)
    ), (
        "the ip chain wearing the ip6 chain's Unreferenced satisfied the "
        "anchors — a reachable chain reported as dead, which is the answer "
        "somebody deletes a live rule on"
    )


def test_a_hardcoded_healthy_pool_fails_the_degraded_anchors() -> None:
    """a5 defects S1/S2/S4, each on the fact it falsifies.

    State is the struct default ONLINE, StatusMessage is never read because
    the pools the port was written against had none, and the two unhealthy
    lists are stubs returning empty slices. A healthy capture catches none of
    it — a hardcoded-healthy collector is RIGHT about a healthy pool — which
    is the whole reason this variant was staged.
    """

    def healthy(facts: dict) -> dict:
        facts["State"] = "ONLINE"
        facts.pop("StatusMessage", None)
        facts["UnhealthyVdevs"] = []
        facts["VdevsWithErrors"] = []
        return facts

    problems = corpus.validate_anchors(
        VARIANTS["storage/degraded"],
        _rewrite(_reference_stream("storage/degraded"), "host-2f5789", healthy),
    )
    for fact in ("State", "StatusMessage", "UnhealthyVdevs", "VdevsWithErrors"):
        assert any(fact in p for p in problems), (
            f"no anchor caught a hardcoded-healthy {fact}. Anchors that "
            f"fired: {problems}"
        )


def test_a_pool_that_reports_its_counters_as_errors_fails_the_anchor() -> None:
    """The other half of the staging, and the one a5 gets right by luck.

    Errors is 0 on this pool BESIDE a non-zero checksum counter, because
    parity repaired every bad block — no data was lost. A subject that sums
    the per-vdev counters into Errors reports three data errors on a pool
    that has none, and a subject that hardcodes 0 happens to agree with the
    staging here. Anchoring the exact value is what tells those two apart,
    and it is why the value is anchored at 0 rather than asserted non-zero.
    """
    problems = corpus.validate_anchors(
        VARIANTS["storage/degraded"],
        _rewrite(
            _reference_stream("storage/degraded"),
            "host-2f5789",
            lambda facts: {**facts, "Errors": 3},
        ),
    )
    assert any("Errors" in p for p in problems), problems
